import React, { useState, useMemo } from "react";
import { geoNaturalEarth1, geoPath } from "d3-geo";
import { feature } from "topojson-client";
import worldTopo from "world-atlas/countries-110m.json";
import { compact, countryName } from "./format.js";

/* ---- world map -------------------------------------------------
   The atlas keys countries by ISO 3166-1 *numeric*; members carry alpha-2.
   This table was generated by matching every atlas country name against ICU's
   own name for each alpha-2 code, then verified: 174 of 177 matched, the three
   left out (N. Cyprus, Somaliland, Kosovo) having no numeric code to match on.
   Withdrawn codes were excluded first, since ICU still answers "Germany" for
   DD and "France" for FX and they would otherwise win the name. */
const ISO_NUMERIC_TO_ALPHA2 = Object.fromEntries(
  ("004:AF,008:AL,010:AQ,012:DZ,024:AO,031:AZ,032:AR,036:AU,040:AT,044:BS,050:BD,051:AM,056:BE,064:BT,068:BO,070:BA,072:BW,076:BR,084:BZ,090:SB,096:BN,100:BG,104:MM,108:BI,112:BY,116:KH,120:CM,124:CA,140:CF,144:LK,148:TD,152:CL,156:CN,158:TW,170:CO,178:CG,180:CD,188:CR,191:HR,192:CU,196:CY,203:CZ,204:BJ,208:DK,214:DO,218:EC,222:SV,226:GQ,231:ET,232:ER,233:EE,238:FK,242:FJ,246:FI,250:FR,260:TF,262:DJ,266:GA,268:GE,270:GM,275:PS,276:DE,288:GH,300:GR,304:GL,320:GT,324:GN,328:GY,332:HT,340:HN,348:HU,352:IS,356:IN,360:ID,364:IR,368:IQ,372:IE,376:IL,380:IT,384:CI,388:JM,392:JP,398:KZ,400:JO,404:KE,408:KP,410:KR,414:KW,417:KG,418:LA,422:LB,426:LS,428:LV,430:LR,434:LY,440:LT,442:LU,450:MG,454:MW,458:MY,466:ML,478:MR,484:MX,496:MN,498:MD,499:ME,504:MA,508:MZ,512:OM,516:NA,524:NP,528:NL,540:NC,548:VU,554:NZ,558:NI,562:NE,566:NG,578:NO,586:PK,591:PA,598:PG,600:PY,604:PE,608:PH,616:PL,620:PT,624:GW,626:TL,630:PR,634:QA,642:RO,643:RU,646:RW,682:SA,686:SN,688:RS,694:SL,703:SK,704:VN,705:SI,706:SO,710:ZA,716:ZW,724:ES,728:SS,729:SD,732:EH,740:SR,748:SZ,752:SE,756:CH,760:SY,762:TJ,764:TH,768:TG,780:TT,784:AE,788:TN,792:TR,795:TM,800:UG,804:UA,807:MK,818:EG,826:GB,834:TZ,840:US,854:BF,858:UY,860:UZ,862:VE,887:YE,894:ZM")
    .split(",")
    .map((p) => p.split(":"))
);

/* Sequential ramp, one hue light→dark, validated against the white card the
   map sits on: monotone lightness, and a light end still clearing 2:1 so "one
   member" cannot be mistaken for "none". Four steps rather than five — the
   same lightness range split fewer ways gives gaps of ~0.17 instead of ~0.10,
   which is the difference between steps you can tell apart at country size and
   steps you cannot. */
const MAP_STEPS = ["#d9ad4e", "#a87227", "#70430f", "#3a2208"];
const bucketOf = (n) => (n >= 5 ? 3 : n - 1);
const BUCKET_LABEL = ["1", "2", "3", "4+"];

// Antarctica is in the atlas but has no members and eats a third of the frame
const WORLD = feature(worldTopo, worldTopo.objects.countries).features.filter((f) => f.id !== "010");

/* Fit to the countries actually drawn, then take the viewBox from their real
   bounds. Fitting to the sphere instead leaves a band of empty ocean where
   Antarctica would have been. */
const MAP_PATH = (() => {
  const collection = { type: "FeatureCollection", features: WORLD };
  const projection = geoNaturalEarth1().fitWidth(900, collection);
  return geoPath(projection);
})();
const MAP_BOX = (() => {
  const [[x0, y0], [x1, y1]] = MAP_PATH.bounds({ type: "FeatureCollection", features: WORLD });
  const pad = 4;
  return `${x0 - pad} ${y0 - pad} ${x1 - x0 + pad * 2} ${y1 - y0 + pad * 2}`;
})();

export default function WorldMap({ t, lang, members }) {
  const [selected, setSelected] = useState(null);

  const byCountry = useMemo(() => {
    const m = new Map();
    members.forEach((x) => {
      const cc = (x.country || "").toUpperCase();
      if (!cc) return;
      if (!m.has(cc)) m.set(cc, []);
      m.get(cc).push(x);
    });
    return m;
  }, [members]);

  const counts = useMemo(
    () =>
      [...byCountry.entries()]
        .map(([cc, list]) => ({ cc, n: list.length, name: countryName(cc, lang) }))
        .sort((a, b) => b.n - a.n || a.name.localeCompare(b.name)),
    [byCountry, lang]
  );

  const noCountry = members.filter((m) => !m.country).length;
  // a country the roster has but the atlas cannot draw would otherwise vanish silently
  const undrawable = counts.filter((c) => !Object.values(ISO_NUMERIC_TO_ALPHA2).includes(c.cc));
  const chosen = selected && byCountry.has(selected) ? selected : null;

  return (
    <section>
      <div className="bt-podium-head">
        <h2 className="bt-h2">{t.mapTitle}</h2>
      </div>
      <p className="bt-timing-intro">{t.mapIntro(counts.length, members.length - noCountry)}</p>

      <div className="bt-map-wrap">
        <svg className="bt-map" viewBox={MAP_BOX} role="img" aria-label={t.mapTitle}>
          {WORLD.map((f) => {
            const cc = ISO_NUMERIC_TO_ALPHA2[f.id];
            const list = cc ? byCountry.get(cc) : null;
            const n = list ? list.length : 0;
            return (
              <path
                key={f.id}
                d={MAP_PATH(f)}
                className="bt-country"
                data-step={n ? bucketOf(n) : undefined}
                data-on={chosen && cc === chosen ? "" : undefined}
                onClick={n ? () => setSelected(cc === chosen ? null : cc) : undefined}
                tabIndex={n ? 0 : undefined}
                role={n ? "button" : undefined}
                onKeyDown={
                  n
                    ? (e) => {
                        if (e.key === "Enter" || e.key === " ") {
                          e.preventDefault();
                          setSelected(cc === chosen ? null : cc);
                        }
                      }
                    : undefined
                }
              >
                {n > 0 && <title>{`${countryName(cc, lang)} — ${t.memberCount(n)}`}</title>}
              </path>
            );
          })}
        </svg>

        <ul className="bt-map-key" aria-hidden="true">
          {MAP_STEPS.map((_, i) => (
            <li key={i}>
              <span className="bt-map-swatch" data-step={i} />
              {BUCKET_LABEL[i]}
            </li>
          ))}
        </ul>
      </div>

      {/* Doubles as the table view: every country and count is readable here
          without interpreting a colour, and it drives the same selection. */}
      <div className="bt-map-cols">
        <ol className="bt-countrylist bt-scrolls">
          {counts.map((c) => (
            <li key={c.cc}>
              <button className="bt-countryrow" aria-pressed={c.cc === chosen} onClick={() => setSelected(c.cc === chosen ? null : c.cc)}>
                <span className="bt-map-swatch" data-step={bucketOf(c.n)} />
                <span className="bt-countryrow-name">{c.name}</span>
                <span className="bt-countryrow-n">{c.n}</span>
              </button>
            </li>
          ))}
        </ol>

        <div className="bt-map-members">
          {chosen ? (
            <>
              <h3 className="bt-map-members-title">
                {countryName(chosen, lang)} <span>{t.memberCount(byCountry.get(chosen).length)}</span>
              </h3>
              <ul className="bt-map-memberlist bt-scrolls">
                {byCountry
                  .get(chosen)
                  .slice()
                  .sort((a, b) => b.might - a.might)
                  .map((m) => (
                    <li key={m.id}>
                      <span className="bt-map-member-name">{m.name}</span>
                      <span className="bt-map-member-rank">{t.ranks[m.rank] || m.rank}</span>
                      <span className="bt-map-member-might">{compact(m.might)}</span>
                    </li>
                  ))}
              </ul>
            </>
          ) : (
            <p className="bt-map-hint">{t.mapHint}</p>
          )}
        </div>
      </div>

      {(noCountry > 0 || undrawable.length > 0) && (
        <p className="bt-rule-note">
          {noCountry > 0 && `${t.noCountry(noCountry)} `}
          {undrawable.length > 0 && t.notOnMap(undrawable.map((c) => c.name).join(", "))}
        </p>
      )}
    </section>
  );
}
